service: helper

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

functions:
  handler:
    handler: index.handler
    events:
      - alexaSkill:
          appId: amzn1.ask.skill.36153e2a-f214-4e29-a08a-373b4e92d3e1
          enabled: true
